# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://minwoo-bae.github.io/
baseurl: /sustain/
title: Minwoo Bae
author: Minwoo Bae
description: Personal hompage 
avatar: profile.png
email: minwoo@mit.edu
github: minwoo-bae/sustain # username
twitter: 
linkedin: 
stackoverflow:    #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: 
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
